"""empty message

Revision ID: 00a36c1a983e
Revises: 384798d610db
Create Date: 2017-08-19 00:11:42.016847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a36c1a983e'
down_revision = '384798d610db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
