"""empty message

Revision ID: 0cf73d3c128c
Revises: 6bc462821445
Create Date: 2017-08-18 23:59:25.938415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf73d3c128c'
down_revision = '6bc462821445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
