"""empty message

Revision ID: 1bd8f12ce572
Revises: f554ba64c56c
Create Date: 2017-08-19 00:06:05.693079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd8f12ce572'
down_revision = 'f554ba64c56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
