"""Adding Nif to fund

Revision ID: 2f324fe924be
Revises: d11668d40499
Create Date: 2017-08-18 23:41:51.786499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f324fe924be'
down_revision = 'd11668d40499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('nif', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'nif')
    # ### end Alembic commands ###
