"""empty message

Revision ID: 384798d610db
Revises: 1bd8f12ce572
Create Date: 2017-08-19 00:07:43.854158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384798d610db'
down_revision = '1bd8f12ce572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
