"""empty message

Revision ID: 3c33c5aadcf3
Revises: 00a36c1a983e
Create Date: 2017-08-19 00:12:25.589541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c33c5aadcf3'
down_revision = '00a36c1a983e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fund_submission', type_='foreignkey')
    op.drop_column('fund_submission', 'fund_nif')
    # ### end Alembic commands ###
