"""Isin code in funds

Revision ID: 50ef04c3b0ff
Revises: d7db6574581d
Create Date: 2017-08-11 23:39:06.287060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ef04c3b0ff'
down_revision = 'd7db6574581d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('isin_code', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'isin_code')
    # ### end Alembic commands ###
