"""empty message

Revision ID: 5b238eb45dba
Revises: 3c33c5aadcf3
Create Date: 2017-08-19 00:14:13.711022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b238eb45dba'
down_revision = '3c33c5aadcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_submission', sa.Column('fund_nif', sa.String(length=45), nullable=False))
    op.create_foreign_key(None, 'fund_submission', 'funds', ['fund_nif'], ['nif'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fund_submission', type_='foreignkey')
    op.drop_column('fund_submission', 'fund_nif')
    # ### end Alembic commands ###
