"""empty message

Revision ID: 6bc462821445
Revises: 2f324fe924be
Create Date: 2017-08-18 23:58:20.157671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc462821445'
down_revision = '2f324fe924be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fund_submission_fund_id_fkey', 'fund_submission', type_='foreignkey')
    op.drop_column('fund_submission', 'fund_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_submission', sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fund_submission_fund_id_fkey', 'fund_submission', 'funds', ['fund_id'], ['id'])
    # ### end Alembic commands ###
