"""empty message

Revision ID: e9c40f136b24
Revises: 50ef04c3b0ff
Create Date: 2017-08-11 23:40:20.947329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c40f136b24'
down_revision = '50ef04c3b0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
