"""empty message

Revision ID: f554ba64c56c
Revises: fd4dd7e15a5e
Create Date: 2017-08-19 00:04:56.921779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f554ba64c56c'
down_revision = 'fd4dd7e15a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
