"""empty message

Revision ID: fd4dd7e15a5e
Revises: 0cf73d3c128c
Create Date: 2017-08-18 23:59:43.970734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4dd7e15a5e'
down_revision = '0cf73d3c128c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
